language: java

dist: trusty

jdk:
  - oraclejdk11
  - oraclejdk-ea
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
  - openjdk16
  - openjdk-ea


cache:
  directories:
  - $HOME/.m2
