= Contributing to Apron

Thanks for your interest in contributing to Apron.

== How to contribute

If you intent to do larger changes it is advisable to open an
https://github.com/poiu-de/apron/issues[Issue] issue first, describing the
problem and the intentions. This helps avoiding duplicate work or your
changes being refused for some reason.

Of course you are free to just fork the project, do the intented changes
and create a pull request.

== What to contribute

=== Finding bugs

Every software has bugs. If you find a bug in Apron please file an
https://github.com/poiu-de/apron/issues[Issue] so they can be resolved.

Preparing pull requests to solve issues is also highly welcome, of course.
In that case, please provide a commit with a unit test demonstrating the
problem and another commit with the actual fix.

=== Writing code

When writing some code please follow our
https://hupfdule.github.io/styleguide/javaguide.html[code conventions].

Please structure your commits logically and respect the original
formatting.  Do not change formattings unrelated to any functional changes,
even if the existing formatting violates the styleguide.  To do such
formatting changes, please prepare a separate pull request.
